export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"


export const SHIPPING_REQUEST = "SHIPPING_REQUEST"
export const SHIPPING_SUCCESS = "SHIPPING_SUCCESS"
export const SHIPPING_FAIL = "SHIPPING_FAIL"
export const SHIPPING_RESET = "SHIPPING_RESET"